import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import SubHeader from "./components/header/SubHeader";
import Head from "next/head";

const poppins = Poppins({ weight: ["300", "600", "900"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <SubHeader />
        {children}
      </body>
    </html>
  );
}
